spring:
  thymeleaf:
    prefix: "classpath:/static/"
    suffix: ".html"
    enabled: true
    cache: false
  datasource:
    url: jdbc:mysql://172.16.70.20:3306/engineering?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: rd_user
    password: NTHXDF7czYwi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    restart:
      enabled: true
      exclude:
  mvc:
    static-path-pattern: "/**"
  resources:
    static-locations: "classpath:/static/"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      whyisee:
        getdata:
          dao: debug

server:
  port: 8089
  servlet:
    context-path: /getdata
    session:
      cookie:
        max-age: 86400

file:
  upload:
    url: "/"
    maxFileSize: "1MB"
    maxRequestSize: "10MB"
  download:
 #   url: "/data/get_data/"
    url: "D:\\Users\\zoukehui\\data\\"