spring:
  thymeleaf:
    prefix: "classpath:/static/"
    suffix: ".html"
    enabled: true
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/getdata?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      exclude:
  mvc:
    static-path-pattern: "/**"
  resources:
    static-locations: "classpath:/static/"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8181
  servlet:
    context-path: /getdata
    session:
      cookie:
        max-age: 86400

file:
  upload:
    url: "F:\\data\\test"
    maxFileSize: "1MB"
    maxRequestSize: "10MB"
  download:
    url: "F:\\data\\test"